// <auto-generated />
namespace SOGIP_v2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class entre_aso_lam : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(entre_aso_lam));
        
        string IMigrationMetadata.Id
        {
            get { return "201809302259075_entre_aso_lam"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
