// <auto-generated />
namespace SOGIP_v2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Inclusión_Nombre1_2Apellido1_2Fecha_Nacimiento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inclusión_Nombre1_2Apellido1_2Fecha_Nacimiento));
        
        string IMigrationMetadata.Id
        {
            get { return "201809261618001_Inclusión_Nombre1_2-Apellido1_2-Fecha_Nacimiento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
