// <auto-generated />
namespace SOGIP_v2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cambio_Nombre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambio_Nombre));
        
        string IMigrationMetadata.Id
        {
            get { return "201809270405546_cambio_Nombre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
