// <auto-generated />
namespace SOGIP_v2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class varbinarymaxparaExp_Fís : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(varbinarymaxparaExp_Fís));
        
        string IMigrationMetadata.Id
        {
            get { return "201810180341154_varbinary(max) para Exp_Fís"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
