// <auto-generated />
namespace SOGIP_v2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tablaCita : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tablaCita));
        
        string IMigrationMetadata.Id
        {
            get { return "201902132337020_tablaCita"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
